from django.db import models

class Transaction(models.Model):
    filename = models.CharField(max_length=500)
    filetype = models.CharField(max_length=1)
    claim_count = models.IntegerField()
    created_date = models.DateField()

    def __str__(self):
        return self.filename
    

class EDICLHP(models.Model):

    BHPNAM = models.CharField(max_length=255, null=True, blank=True)
    BHNPI = models.CharField(max_length=255, null=True, blank=True)
    BHTXID = models.CharField(max_length=255, null=True, blank=True)
    BHPAD1 = models.CharField(max_length=255, null=True, blank=True)
    BHPCTY = models.CharField(max_length=255, null=True, blank=True)
    BHPST = models.CharField(max_length=255, null=True, blank=True)
    BHPZIP = models.CharField(max_length=255, null=True, blank=True)
    BHCFID = models.CharField(max_length=255, null=True, blank=True)
    BHGRPN = models.CharField(max_length=255, null=True, blank=True)
    BHGRNM = models.CharField(max_length=255, null=True, blank=True)
    BHMFNM = models.CharField(max_length=255, null=True, blank=True)
    BHMLNM = models.CharField(max_length=255, null=True, blank=True)
    BHMINT = models.CharField(max_length=255, null=True, blank=True)
    BHMAD1 = models.CharField(max_length=255, null=True, blank=True)
    BHMCTY = models.CharField(max_length=255, null=True, blank=True)
    BHMST = models.CharField(max_length=255, null=True, blank=True)
    BHMZIP = models.CharField(max_length=255, null=True, blank=True)
    BHMBDT = models.CharField(max_length=255, null=True, blank=True)
    BHMSEX = models.CharField(max_length=255, null=True, blank=True)
    BHMID = models.CharField(max_length=255, null=True, blank=True)
    BHORGN = models.CharField(max_length=255, null=True, blank=True)
    BHCHGA = models.CharField(max_length=255, null=True, blank=True)
    BHPLSR = models.CharField(max_length=255, null=True, blank=True)
    BHFREQ = models.CharField(max_length=255, null=True, blank=True)
    BHACPA = models.CharField(max_length=255, null=True, blank=True)
    BHDASG = models.CharField(max_length=255, null=True, blank=True)
    BHRELI = models.CharField(max_length=255, null=True, blank=True)
    BHDMRE = models.CharField(max_length=255, null=True, blank=True)
    BHRECD = models.CharField(max_length=255, null=True, blank=True)
    BHBFRD = models.CharField(max_length=255, null=True, blank=True)
    BHBTOD = models.CharField(max_length=255, null=True, blank=True)
    BHLDWK = models.CharField(max_length=255, null=True, blank=True)
    BHDOCN = models.CharField(max_length=255, null=True, blank=True)
    BHADJR = models.CharField(max_length=255, null=True, blank=True)
    BHNOTC = models.CharField(max_length=255, null=True, blank=True)
    BHNOTE = models.TextField(null=True, blank=True)
    BHDIO1 = models.CharField(max_length=255, null=True, blank=True)
    BHCAMT = models.CharField(max_length=255, null=True, blank=True)
    BHPPOI = models.CharField(max_length=255, null=True, blank=True)
    BHREV = models.CharField(max_length=255, null=True, blank=True)
    BHSNAM = models.CharField(max_length=255, null=True, blank=True)
    BHSAD1 = models.CharField(max_length=255, null=True, blank=True)
    BHSCTY = models.CharField(max_length=255, null=True, blank=True)
    BHSST = models.CharField(max_length=255, null=True, blank=True)
    BHSZIP = models.CharField(max_length=255, null=True, blank=True)
    BHDFNM = models.CharField(max_length=255, null=True, blank=True)
    BHDLNM = models.CharField(max_length=255, null=True, blank=True)
    BHDINT = models.CharField(max_length=255, null=True, blank=True)
    BHDAD1 = models.CharField(max_length=255, null=True, blank=True)
    BHDCTY = models.CharField(max_length=255, null=True, blank=True)
    BHDST = models.CharField(max_length=255, null=True, blank=True)
    BHDZIP = models.CharField(max_length=255, null=True, blank=True)
    BHDBDT = models.CharField(max_length=255, null=True, blank=True)
    BHDSEX = models.CharField(max_length=255, null=True, blank=True)
    BHDIO2 = models.CharField(max_length=255, null=True, blank=True)
    BHPHNM = models.CharField(max_length=255, null=True, blank=True)
    BHPHID = models.CharField(max_length=255, null=True, blank=True)
    BHTAXO = models.CharField(max_length=255, null=True, blank=True)
    BHDIO3 = models.CharField(max_length=255, null=True, blank=True)
    BHDIO4 = models.CharField(max_length=255, null=True, blank=True)
    BHDIO5 = models.CharField(max_length=255, null=True, blank=True)
    BHOICO = models.CharField(max_length=255, null=True, blank=True)
    BHOIDE = models.CharField(max_length=255, null=True, blank=True)
    BHNPA1 = models.CharField(max_length=255, null=True, blank=True)
    BHOPPA = models.CharField(max_length=255, null=True, blank=True)
    BHMEDA = models.CharField(max_length=255, null=True, blank=True)
    BHCALA = models.CharField(max_length=255, null=True, blank=True)
    BHOICP = models.CharField(max_length=255, null=True, blank=True)
    BHNPR2 = models.CharField(max_length=255, null=True, blank=True)
    BHNPA2 = models.CharField(max_length=255, null=True, blank=True)
    BHNOTE2 = models.TextField(null=True, blank=True)
    BHCCBT = models.CharField(max_length=255, null=True, blank=True)
    BHCNTN = models.CharField(max_length=255, null=True, blank=True)
    BHSNDI = models.CharField(max_length=255, null=True, blank=True)
    BHPAYC = models.CharField(max_length=255, null=True, blank=True)
    BHPARN = models.CharField(max_length=255, null=True, blank=True)
    BHRCVI = models.CharField(max_length=255, null=True, blank=True)
    BHAMDG = models.CharField(max_length=255, null=True, blank=True)
    BHSNPI = models.CharField(max_length=255, null=True, blank=True)
    BHCNCD = models.CharField(max_length=255, null=True, blank=True)
    BHOIAL = models.CharField(max_length=255, null=True, blank=True)
    mem_dob = models.CharField(max_length=255, null=True, blank=True)
    dep_dob = models.CharField(max_length=255, null=True, blank=True)
    BHSQCL = models.CharField(max_length=255, null=True, blank=True)
    TEDSSN = models.CharField(max_length=255, null=True, blank=True)
    BHCLNT = models.CharField(max_length=255, null=True, blank=True)
    BHPSEQ = models.CharField(max_length=255, null=True, blank=True)
    BHMEMN = models.CharField(max_length=255, null=True, blank=True)
    BHRLTN = models.CharField(max_length=255, null=True, blank=True)
    BHDREL = models.CharField(max_length=255, null=True, blank=True)
    BHDEPN = models.CharField(max_length=255, null=True, blank=True)
    BHDCNT = models.CharField(max_length=255, null=True, blank=True)
    BHREFC = models.CharField(max_length=255, null=True, blank=True)
    BHTXSN = models.CharField(max_length=255, null=True, blank=True)
    BHCLTP = models.CharField(max_length=255, null=True, blank=True)
    filename = models.CharField(max_length=100,null=True,blank=True)
    class Meta:
        db_table = "ediclhp"


class Fund_Data(models.Model):
    FUND = models.CharField(max_length=255, null=True, blank=True)
    CLAIMS = models.CharField(max_length=255, null=True, blank=True)
    PAID = models.CharField(max_length=255, null=True, blank=True)
    fund_type = models.CharField(max_length=255, null=True, blank=True)
    filename = models.CharField(max_length=255, null=True, blank=True)
    file_date = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        db_table = "fund_data"